services:
  client:
    image: slack-standup-client
    build: client/
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - path: ./client/.env

  server:
    image: slack-standup-server
    build: server/
    ports:
      - 127.0.0.1:4000:4000
    env_file:
      - path: ./server/.env
    environment:
      - DATABASE_HOST=db

  db:
    image: postgres:15.5
    volumes:
      - sb-pg-data:/var/lib/postgres/data
    env_file:
      - path: ./server/.env

volumes:
  sb-pg-data:
