services:
  server:
    build: server/
    ports:
      - 127.0.0.1:4000:4000
    env_file:
      - path: ./server/.env
    environment:
      - DATABASE_HOST=db

  db:
    image: postgres:15.5
    volumes:
      - sb-pg-data:/var/lib/postgres
    env_file:
      - path: ./server/.env

volumes:
  sb-pg-data:
